connector.name=clickhouse
connection-url=jdbc:clickhouse://clickhouse-production-3e5b.up.railway.app:443/railway?ssl=true&sslmode=none
connection-user=clickhouse
connection-password=${CLICKHOUSE_PASSWORD}