connector.name=clickhouse
connection-url=jdbc:clickhouse://${CLICKHOUSE_HOST:-localhost}:${CLICKHOUSE_PORT:-8123}/${CLICKHOUSE_DATABASE:-default}
connection-user=${CLICKHOUSE_USER:-default}
connection-password=${CLICKHOUSE_PASSWORD:-}
