connector.name=iceberg

# Iceberg REST catalog (Cloudflare R2 Data Catalog)
# Tokens baked in at image build time
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=https://catalog.cloudflarestorage.com/203a605533f37eb35da80dcf03a7bed6/gyhc40sdz8-ivj8v3841x-bronze-storage
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.credential=cfat_fiwyQ9W7g7GeujVmDQ43Z23IJbPtv7kY7y4mN9xx4734743e
iceberg.rest-catalog.oauth2.token=cfat_fiwyQ9W7g7GeujVmDQ43Z23IJbPtv7kY7y4mN9xx4734743e
